[icon]
prepend_dirs = [
    { name = "Github", text = "î—»", fg = "#009688" },
]
prepend_conds = [
	{ if = "hidden & dir",  text = "ğŸ‘»" },
	{ if = "dir",           text = "ğŸ“" },
	{ if = "!(dir | link)", text = "ğŸ“„" },
]
