[colors.primary]
background = '#1a1110'
foreground = '#f1dedd'
 
[colors.cursor]
text = '#f1dedd'
cursor = '#d8c2bf' 
 
[colors.vi_mode_cursor]
text = '#1a1110'
cursor = '#ffb3ad' 
 
[colors.search.matches]
foreground = '#534342' 
background = '#e1c28c' 
 
[colors.search.focused_match]
foreground = '#534342' 
background = '#ffb3ad' 
 
[colors.footer_bar]
foreground = '#534342' 
background = '#f1dedd' 
 
[colors.hints.start]
foreground = '#534342' 
background = '#e7bdb9' 
 
[colors.hints.end]
foreground = '#534342' 
background = '#e7bdb9' 
 
[colors.selection]
text = '#1a1110'
background = '#ffb3ad'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb3ad' 
yellow = '#904a45' 
blue = '#ffb3ad' 
magenta = '#e1c28c' 
cyan = '#e7bdb9' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
