[colors.primary]
background = '#0e1513'
foreground = '#dee4e0'
 
[colors.cursor]
text = '#dee4e0'
cursor = '#bfc9c4' 
 
[colors.vi_mode_cursor]
text = '#0e1513'
cursor = '#85d6c0' 
 
[colors.search.matches]
foreground = '#3f4945' 
background = '#aacbe3' 
 
[colors.search.focused_match]
foreground = '#3f4945' 
background = '#85d6c0' 
 
[colors.footer_bar]
foreground = '#3f4945' 
background = '#dee4e0' 
 
[colors.hints.start]
foreground = '#3f4945' 
background = '#b1ccc3' 
 
[colors.hints.end]
foreground = '#3f4945' 
background = '#b1ccc3' 
 
[colors.selection]
text = '#0e1513'
background = '#85d6c0'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#85d6c0' 
yellow = '#0b6b59' 
blue = '#85d6c0' 
magenta = '#aacbe3' 
cyan = '#b1ccc3' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
