general.import = ["alacritty-colors.toml"]

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.7

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }

size = 17.0

[env]
TERM = "xterm-256color"

[window.dimensions]
columns = 90
lines = 28

[keyboard]
bindings = [{ key = "Slash", mods = "Control", chars = "\u001f" }]
